train_data_path: "data/sst2/train.jsonl"
test_data_path: "data/sst2/dev_subsample.jsonl"
n_shot: 4
label_mapping: {'0': 'negative', '1': 'positive'}
corpus_params: {'sentence_1_str': 'sentence', 'label_str': 'label'}
template: "f'Review: {sentence_1}\\nSentiment: {label_text}\\n\\n'"
sample_mode: "balance"
sentence_pair: False