train_data_path: "data/subj/train.jsonl"
test_data_path: "data/subj/dev_subsample.jsonl"
n_shot: 4
label_mapping: {'0': 'subjective', '1': 'objective'}
corpus_params: {'sentence_1_str': 'sentence', 'label_str': 'label'}
template: "f'Input: {sentence_1}\\nType: {label_text}\\n\\n'"
sample_mode: "balance"
sentence_pair: False