# C-Eval 配置（question, A, B, C, D, answer -> choice_a~d 在 load_ceval_cmmlu_ds 中处理）
task_name: "ceval"
split_token: "\n\n"  # ICD之间的分隔符
template: ${infer_model.prompt_templates.ceval_prompt_template}
column_token_map:
  question: "<Q>"
  answer: "<A>"
  choice_a: "<a>"
  choice_b: "<b>"
  choice_c: "<c>"
  choice_d: "<d>"

input_columns: ["question", "choice_a", "choice_b", "choice_c", "choice_d"]
output_column: "answer"
mask_column_token_map: "answer"

gen_args:
  gen_length: 2
  steps: 2
  block_length: 2
  mask_length: 2
  mc_num: 1

